xapi-project/xapi-project.github.io

- _layouts/design_docs_list.html
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>
> Group design docs by their 'status' field

- xapi/futures/ocfs2/ocfs2.md
> ocfs2: add more impacts to the doc

- index.md
- xapi/futures/database/distributed-database.md
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>
> Fix broken image links

- xen-api/extensions.md
- xen-api/overview.md
- xen-api/usage.md
Use `pandoc -t markdown_github` to render these properly.
> Fix tables in XenAPI docs

- _data/navbar.yml
- networkd/overview.md
> High-level networkd architecture

- _data/navbar.yml
- features/backtraces.md
It's clearly not a "high-level feature" in the same class as DR, HA
> Make the backtraces doc a design

- xapi/futures/database/local-database.md
This is a stepping-stone on the way to a full distributed
database.
> Add a simple local database design

- xapi/design/tunnelling.md
> Minor improvements to the tunnelling doc

- xen-api/futures/virt-hw-platform-vn/virt-hw-platform-vn.md
> Design doc for Virtual Hardware Platform Version management

- .travis-ci.sh
- features/HA/HA.md
- index.md
The arguments understood by htmlproof appear to have changed.
> Update travis-ci.sh for html-proofer 2.x

- xen-api/futures/virt-hw-platform-vn/virt-hw-platform-vn.md
> Virtual Hardware Platform: changes missed from prev commit

- xen-api/futures/virt-hw-platform-vn/virt-hw-platform-vn.md
> Virtual Hardware Platform: fix editing-errors.

- xenopsd/walkthroughs/VM.start.md
Signed-off-by: Euan Harris <euan.harris@citrix.com>
> VM.start walkthrough: Fix bullet lists

- xen-api/classes/pbd-currently_attached.md
> Add more explanation for PBD.currently_attached

- xenopsd/design/suspend-image-considerations.md
Signed-off-by: Ravi Pandey <ravi.pandey@citrix.com>
> A few improvements

- xapi/futures/patches-in-vdis/patches-in-vdis.md
> Propose design for placing patches in VDIs

- _data/xenapi.json
- _layouts/xenapi.html
- xen-api/networking.md
> Update some XenAPI tags

- _data/releases.yml
- xen-api/releases/cream.md
- xen-api/releases/dundee.md
> Add cream and dundee releases

- _data/navbar.yml
- _data/xenapi.json
- xen-api/memory.md
> Add a memory page to the xen-api section

- xapi/futures/emulated-pci-spec.md
> Specifying emulated PCI devices: first-draft design

- _data/navbar.yml
- xenopsd/design/hooks.md
> Add some info about xenopsd hooks

- xapi/design/fcoe-nics.md
> Design Doc for NIC supporting FCoE

- xapi/design/fcoe-nics.md
> Design changes for FCoE support

- features/RDP.md
Design doc for on/off control of guest RDP service
> Design for on/off control of guest RDP service

- xapi/futures/thin-lvhd/thin-lvhd.md
> Updates to the thin-lvhd design, showing xapi managing the xenvm daemon

- xapi/design/fcoe-nics.md
> Design changes for FCoE support V3

- _layouts/base.html
- features/futures/gpu-support-evolution.md
Add some details on how we will store assignments of vGPUs to pGPUs at
VM start time.
> Additions to xapi part of GPU evolution design

- xapi/design/multiple-cluster-managers.md
> Add a proposal for multiple cluster managers

- rrdd/futures/sr-level-rrds.md
> Design for "SR-Level RRDs"

- rrdd/futures/sr-level-rrds.md
> SR-Level RRDs v2

- rrdd/futures/sr-level-rrds.md
> SR-Level RRDs v3

- features/futures/aggr-storage-reboots.md
> Design: aggregated local storage and reboots

- rrdd/futures/sr-level-rrds.md
> SR-Level RRDs v4

- features/futures/aggr-storage-reboots.md
> Design: aggregated local storage and reboots v2

- rrdd/futures/sr-level-rrds.md
> Revision 5 of SR level RRDs

- rrdd/futures/sr-level-rrds.md
> Flesh out the framing protocol

- xapi/design/pif-properties.md
> Fix bullet list in PIF properties doc

- xapi/design/multiple-cluster-managers.md
> Multiple cluster managers design v2

- features/futures/aggr-storage-reboots.md
> Design: aggregated local storage and reboots v3

- rrdd/futures/sr-level-rrds.md
- xapi/futures/smapiv3/smapiv3.md
Attempt to simplify the semantics of querying SR and VM RRD updates,
without breaking backwards compatibility.
> Another rework of the rrd_updates API

- _data/navbar.yml
- devguide/howtos/add-api-extension.md
Signed-off-by: David Scott <dave.scott@eu.citrix.com>
> Add XenAPI extension doc to the XenAPI guide

- rrdd/futures/sr-level-rrds.md
> Adding details of all new APIs added to xapi and xcp-rrdd

- xapi/design/cpu-levelling-v2.md
Signed-off-by: Euan Harris <euan.harris@citrix.com>
> cpu-levelling: Add list of included and excluded use cases

- xapi/design/cpu-levelling-v2.md
> Another CPU levelling v2 update

- xapi/design/cpu-levelling-v2.md
> Levelling v2: RPU update

- xapi/futures/thin-lvhd/thin-lvhd.md
Add some documentation of the ring protocol and the cap request
> Thin lvhd ring protocol and cap

- xapi/futures/pool-wide-ssh/pool-wide-ssh.md
> Add pool-wide ssh design draft

- xapi/design/schedule-snapshot.md
> CP-15502: Schedule Snapshot Design

- xapi/design/schedule-snapshot.md
> VM Schedule Snapshot Design changes v2

- xapi/design/schedule-snapshot.md
> Remove alarm config from VMSS design

- xapi/design/schedule-snapshot.md
> Name changes in fields for VM scheduled snapshot design

- _data/navbar.yml
- xen-api/basics.md
- xen-api/wire-protocol.md
> Update XenAPI introductory pages

- xapi/design/management-interface-on-vlan.md
> Add a design for Management Interface on VLAN

- xapi/design/management-interface-on-vlan.md
> Update network_db for VLAN info needed for Upgrade

- xapi/design/management-interface-on-vlan.md
> More info on networkd_db and API Errors

- xapi/design/schedule-snapshot.md
> CP-16190: Add an API to set the status of Task

- _data/navbar.yml
- devguide/howtos/add-class.md
Using `PVS farm` as an example.
Signed-off-by: Christian Lindig <christian.lindig@citrix.com>
> CP-17799 document adding a new class to Xen API

- _data/releases.yml
- xen-api/releases/ely.md
- xen-api/releases/falcon.md
We have to manually create these files and modify releases.yml when a
new XenServer is released.
> CA-256509: Add missing Ely and Falcon releases

- xen-api/classes/Feature.md
- xen-api/classes/PVS_cache_storage.md
- xen-api/classes/PVS_proxy.md
- xen-api/classes/PVS_server.md
- xen-api/classes/PVS_site.md
- xen-api/classes/SDN_controller.md
- xen-api/classes/VMSS.md
- xen-api/classes/pool_update.md
> CA-256509: Add missing XenAPI classes

- xen-api/classes/vdi_nbd_server_info.md
> Add new vdi_nbd_server_info class

- _data/releases.yml
- xen-api/releases/inverness.md
> XSO-828: add missing Inverness release

- xen-api/classes/PUSB.md
- xen-api/classes/USB_group.md
- xen-api/classes/VUSB.md
> Add missing XenAPI classes

- _data/releases.yml
- xen-api/releases/jura.md
> Add Jura release

- devguide/howtos/add-function.md
Added information describing more paramaters on the devguid/howtos/add-function page. 
Changed the syntax for the example of ~params to use () on tuples to better reflect the codebase
Added details of more parameters used create call
> Added information to the add-function page

- devguide/howtos/add-function.md
Signed-off-by: Steven Woods <steven_96-@hotmail.com>
> Add missing statement about adding to the mli

- xen-api/metrics.md
This not only explains how to control the format, but also recommends using session tokens instead of HTTP basic authentication..
Depends on https://github.com/xapi-project/xen-api/pull/5090 being merged, probably should explain the accept header is only read in versions after 23.17.0
> metrics: Explain how to fetch metrics in json format

- features/futures/pci-passthrough.md
PR attempt: https://github.com/xapi-project/xen-api/pull/5503
So here's a design proposal for the PR mentionned above. I guess it's simpler to discuss everything here and I'll make the change accordingly.
For the tests we'll implement them in our test repo for our internal CI but I still described them here.
> Design proposal for PCI passthrough API

- features/futures/pci-passthrough.md
See: https://github.com/xapi-project/xapi-project.github.io/pull/286
> PCI passthrough has been released

- .github/workflows/pull-xapi-data.yml
Now it's up-to-date with latest xapi's master location
> CI: change location of the docs directory

- .github/workflows/pull-xapi-data.yml
This fixes the compatibility with Ubuntu 24.04
> github: use latest setup-ocaml action
