- xen-api/futures/virt-hw-platform-vn/virt-hw-platform-vn.md
* Change naming-scheme
* Describe first use-case
* Describe limitation (new VMs on pre-feature hosts)
* Give host [0] not [] by default, to avoid special-case for VM ver 0
> Virtual Hardware Platform Version: design updates

- xapi/futures/thin-lvhd/queue.pml
In particular we send two kinds of updates
- sync: a full update
- delta: a difference since the last update
We expect a full sync to be send on resume and at no other time.
> Add a simple promela model of the queue suspend/resume protocol

- xapi/futures/thin-lvhd/thin-lvhd.md
Use of - for range and for minus is a bit confusing...
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>
> Make octect ranges unambiguous

- xen-api/classes/vm_memory_overhead.md
Note this field is incorrectly named VM.overhead: #100
> Add better docs for VM.memory_overhead

- _data/navbar.yml
- _layouts/base.html
Repurpose the top menu bar to divide the information contained in the site into three parts:
- XenAPI user documentation
- Architectural documentation
- Design docs (proposals)
This may make the top menu more useful, and reduces the amount of stuff in the menu on the left.
(just requesting feedback for now... the navbar isn't quite right yet)
> RFC: reorganisation

- xapi/futures/thin-lvhd/thin-lvhd.md
Signed-off-by: Euan Harris <euan.harris@citrix.com>
> thin-lvhd: xenvmd exports RRDs, not local_allocator

- xapi/futures/xenprep.md
Just updating a string. The new choice fits better with the conventions
used for the existing error strings.
> Error VBD_XENPREP_CD_IN_USE, not XENPREP_IN_PROGRESS

- rrdd/futures/sr-level-rrds.md
Changing in magic number from 0xda7ada7a to 0x7ada7ada.
Magic number must fit into Int32.
> Magic number change in framing format of vdi

- assets/css/xenapi.css
They can still be hidden by clicking on "Show/hide implicit".
> XenAPI docs: Show implicit messages by default

- xen-api/usage.md
Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>
Summary: The old PS snapin was removed after clearwater. The new PS snapin was replaced by a PS module as of creedence. The target .NET framework is currently 4.5.
> CP-18032: Updated the language bindings bit of the API usage guide.

- xen-api/overview.md
When I followed the original instructions, the VM.provision call failed,
because the UUID of the Storage Repository to use is set to "" by
default. This commit adds a step to set the sr property in the piece of
XML stored under the "disks" key in the other_config map of the VM.
> CA-226006 Update steps to install VM from template

- xenopsd/walkthroughs/VM.start.md
The numbering of the steps in the walkthrough is incorrect: most items
begin with a "1.". Apparently using a different syntax for markdown
headers fixes the issue.
> Xenopsd walkthrough: fix numbering of steps

- _layouts/base.html
error message was:
```
Liquid Warning: Liquid syntax error (line 5): Unexpected character } in "page.title }" in /_layouts/base.html
```
> fix html.head.title

- profiling/coverage.md
For use in xapi/xenopsd, see https://github.com/xapi-project/xcp-idl/pull/179 for an implementation.
This PR just updates the coverage design for the new runtime dumping, it doesn't update it for all the jbuilder changes, I think that could be done in a separate PR.
> CP-22945: update design for runtime coverage dumping

- .github/workflows/pull-xapi-data.yml
I'm not sure why this failure doesn't happen on xen-api. It's also a strange one: the server serves a 404 when asked for the .debs but the action keeps happily chugging along until the packages try to compile against those libraries.
https://github.com/ocaml/setup-ocaml/issues/633
Also update the env-setting action
> ci: update ubuntu repositories to avoid failure

- .github/workflows/pull-xapi-data.yml
The latest dotenv action is v1.0.2. v1 is aliased now to this version and it will be updated if a newer version is released
The warnings can be seen here, they will become errors soon enough: https://github.com/xapi-project/xapi-project.github.io/actions/runs/4050179438
> ci: update actions to supress warnings

- rrdd/design/plugin-protocol-v2.md
This is missing the values of the units field. I think this is somewhat open but dependent on what the consumer can display (e.g. XenCenter)?
> Updates to the RRDD protocol design document

- _data/navbar.yml
- devguide/howtos/use-forwarded.socket.md
Some daemons (xcp-rrdd, xenopsd, others ?) uses .forwarded sockets, but it is explained nowhere how they works and interact with the rest of XAPI world.
Add a small documentation on those sockets for development purposes.
> Explain how works *.forwarded sockets.

- xen-api/metrics.md
In particular explains default behaviour using wget and curl, as well as fixing the format for the 'accept any' value
> metrics: add more detail to the format selection

- rrdd/design/plugin-protocol-v3.md
Propose a new plugin protocol for OpenMetrics support and that is meant to be simpler to implement for plugins and parsers.
It uses OpenMetrics binary format (based on Protocol Buffers) that can be easily quite easily parsed and generated using reference or third-party protocol buffers implementations :
- https://protobuf.dev/overview/
- https://github.com/protocolbuffers/protobuf/blob/main/docs/third_party.md
It could be interesting to consider implementations for various programming languages in the future, as protocol buffers is quite well supported and protocol format is pretty simple.
> Propose RRDD Protocol v3.

- .github/workflows/pull-xapi-data.yml
The CI doesn't install these, only builds them so pick their location accordingly
> CI: copy docs build location, not the install location

- .github/workflows/pull-xapi-data.yml
Now opam install is invoked in the same way as in xen-api.git
This should fix the nightly pulls
> github: update workflow to latest xapi and actions
